name: Deploy Flask App to Elastic Beanstalk via CDK

on:
  push:
    branches:
      - main  # Deploy only when main is pushed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Python (for CDK app)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "No Flask runtime deps for CDK"
          pip install aws-cdk-lib constructs boto3

      # 4️⃣ Install AWS CDK CLI globally
      - name: Install AWS CDK CLI
        run: npm install -g aws-cdk

      # 5️⃣ Build your Flask app zip
      - name: Build Flask zip
        run: |
          chmod +x build.sh
          ./build.sh

      # 6️⃣ Configure AWS credentials (from GitHub secrets)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 7️⃣ Deploy using CDK
      - name: Deploy CDK Stack
        working-directory: ./cdk
        run: |
          cdk bootstrap
          cdk deploy --require-approval never
